name: Calendar

permissions:
  contents: write
  id-token: write

on:
  push:
    tags:
      - "**"
  schedule:
    - cron: '0 0 1 * *'
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Build
      run: cargo run --verbose
    - name: Get current date
      id: current_date
      run: echo "CURRENT_DATE=$(date +'%Y-%m-%d')" >> $GITHUB_ENV
    - name: Create release with unique tag
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: "${{ github.ref_name }}-${{ env.CURRENT_DATE }}"  # Adding date to the tag
        release_name: "Release ${{ github.ref_name }} - ${{ env.CURRENT_DATE }}"
        draft: false
        body: ""
        prerelease: false
    - name: Upload artifact
      uses: actions/upload-release-asset@v1.0.2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./out/steam_sales.ics
        asset_name: steam_sales.ics
        asset_content_type: text/calendar
