name: Steam Sales Scraper

# Grant the GitHub Actions token write access to repository contents
permissions:
  contents: write

on:
  schedule:
    - cron: '0 0 * * *'  # Runs every day at midnight (UTC)
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install selenium webdriver-manager

      # Optional: Install Google Chrome if needed (most ubuntu-latest images have Chrome pre-installed)
      - name: Install Google Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable

      # Step 4: Run the scraper script
      - name: Run steam sales scraper
        run: python Events.py

      # Step 5: Commit and push the output file (sales_data.txt)
      - name: Commit and push sales data file
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add sales_data.txt
          git commit -m "Update sales data" || echo "No changes to commit"
          git push origin HEAD:main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
